Alpha
bmstu-iu9/utp2020-3-2d-game pull request #25
Opened 2020-09-12 19:00 UTC by Snake5932

2020-09-15 09:36 UTC, frussian requested changes

2020-09-15 09:36 UTC, frussian commented on Camera.js
> +    /*if (leftPressed && worldToCanvas(player.realXCenter, 0) <= canvas.width / 2) {
уже можно удалить?

2020-09-15 09:36 UTC, frussian commented on FigureCollision.js
> +let pointInRect = (x, y, xR, yR, h, w) => {
тут сделать const

2020-09-15 09:36 UTC, frussian commented on GrenadeCollision.js
> +let grenadeCollision = () => {
const

2020-09-15 09:36 UTC, frussian commented on MainLoop.js
>  const drawTileTypes = () => {
думаю это уже не пригодится

2020-09-15 09:36 UTC, frussian commented on MainLoop.js
> +    if (v || performance.now() - target.lastTimeSeen < 200) {
200 назвать как-нибудь

2020-09-15 09:36 UTC, frussian commented on PlayerCollision.js
> +let collisionPlayer = (x, y, w, h) => {
const

2020-09-15 09:36 UTC, frussian commented on Target.js
> +                  canvasToWorld(sight.x, 0), canvasToWorld(sight.y, 1)) > 1.5) {
1.5 тоже

2020-09-15 09:36 UTC, frussian commented on Target.js
> +    if (dist(player.realXCenter, this.plUpdX, player.realYCenter, this.plUpdY) > 100) {
100 назвать как-нибудь

2020-09-15 09:36 UTC, frussian commented on Target.js
> +        if (d < 250) {
много констант

2020-09-15 09:36 UTC, frussian commented on GamePlayer.js
> +  ctx.beginPath();
вот эту отрисовку убрать

2020-09-15 09:36 UTC, frussian commented on GamePlayer.js
>      this.x = x;
лишние координаты вроде нигде не используются, думаю можно убрать

2020-09-15 09:36 UTC, frussian commented on GamePlayer.js
>      this.weapon = new Weapon(2);
Вернуть м16

2020-09-16 17:03 UTC, Snake5932 commented on MainLoop.js
>  const drawTileTypes = () => {
drawTileTypes?

2020-09-16 17:03 UTC, Snake5932 commented on Target.js
> +        if (d < 250) {
всего одна - 250

2020-09-16 17:08 UTC, frussian commented on MainLoop.js
>  const drawTileTypes = () => {
да

2020-09-16 17:09 UTC, Snake5932 commented on GamePlayer.js
>      this.x = x;
какие именно?

2020-09-16 17:09 UTC, frussian commented on Target.js
> +        if (d < 250) {
там ниже еще

2020-09-16 18:12 UTC, frussian commented on GamePlayer.js
>      this.x = x;
X/Y_Center

2020-09-19 17:38 UTC, frussian submitted a review, later dismissed

2020-09-20 12:30 UTC, frussian submitted a review, later dismissed

2020-09-20 13:02 UTC, frussian approved these changes

2020-09-20 13:03 UTC, merged